let p = dom.create('<p>我是前端新人</p>') //创建了一个dom对象
document.body.appendChild(p)
let first = document.querySelector("#first")
dom.after(first, "<div>1</div>")
dom.before(p, '<span>我是马青云</span>')
let div1 = dom.create('<div1>2</div>')
dom.append(first, div1)
let c = document.querySelector("#empty")
dom.empty(c)
let gai = document.querySelector('.gai')
dom.attr(gai, 'color', ' red')
dom.text(gai, '改文本内容')
console.log(dom.text(gai))
dom.style(gai, 'color', 'red')
console.log(dom.style(gai, 'color'))
dom.style(gai, { border: '1px solid red' })
dom.class.add(c, 'blue')
dom.class.has(c, 'blue')
dom.on(gai, 'click', () => { console.log('点击了') })
let b = dom.find('#find2')[0]
let a = dom.find('.f', b)
console.log(a)
console.log(dom.siblings(find2))

console.log('123', b)
dom.each(dom.children(b), (n) => dom.style(n, 'color', 'red'))

let bIndex = dom.index(b)
console.log("bIndex", bIndex)